### ISSUE TITLE
Template option feature proposal

### ISSUE THREAD

**Issue by 1000ch** [t32k/stylestats#104]
`--template template-file-path` (alias: `-t`)
`--format (json|md|html|csv)` (alias: `-f`)

Underscore style is used as template notation in StyleStats now, but it is not simple.
Handlebars or Mustache style is better, I think.

related to #103

**Comment by jmblog** [comment]
I'd like to specify the extension of the generated file with the template file. For example, if I want to generate the file `example.markdown` via `example.css`, the name of template file would be `template.markdown`. What do you think?

And about the template engine, I like handlebars. :)

**Comment by t32k** [comment]
How about we use redirection? I'd like to keep it simple.

```
stylestats foo.css --template /path/to/template > foo.md
```

I also like Handlebars. :+1:

**Comment by jmblog** [comment]
+1

**Comment by 1000ch** [comment]
`--format` options is for current `--type` compatibility.

**Comment by t32k** [comment]
#105

**Comment by t32k** [comment]
Released.
