### ISSUE TITLE
Prettify data

### ISSUE THREAD

**Issue by jmblog** [t32k/stylestats#106]
Are there any reason that you prettify data in only some format? I'm happy if I can get prettified data in Markdown.

**Comment by t32k** [comment]
StyleStats v4.3 supports markdown output.
https://github.com/t32k/stylestats/releases/tag/v4.3.0

However, it might be different what you want, and someone wanted another markdown format like table in markdown, not list.

We can't support formats everyone wants, so we adopted your template feature to solve the problem at v5.0.0. The feature enables them to get formats they want.

**Comment by jmblog** [comment]
@t32k I mean the prettified data by [prettify.js](https://github.com/t32k/stylestats/blob/develop/lib/prettify.js). For example, not `ratioOfDataUriSize` but `Ratio of Data URI Size` is good for me. As you mentioned, nicer markdown style will be gotten at v5.0.0. It' really helpful for me!

What do you think of such as a  `--prettify` option or a `--raw` option for raw data? Is this a little bit complex?

**Comment by t32k** [comment]
I misunderstood. Actually, it sounds good. I'll think about it.:)

**Comment by jmblog** [comment]
:bow:
