### ISSUE TITLE
[ERROR ] CSS Parse Error in a globbing path

### ISSUE THREAD

**Issue by enricforn** [t32k/stylestats#110]
When source path to analyze are multiple files (e.g. stylestats ./sourcepath/*_/_.css), if there is one file with a parse error, you don't know which file has that error.

Would be very useful to add file path with parse error, in this case you know which file you have to fix. Example of desired message:

[ERROR] CSS Parse error in file ./sourcepath/fileWithBadParsing.css

**Comment by t32k** [comment]
Related to #114.

**Comment by t32k** [comment]
It may take somehow time to modify the code in order to know the file has error.
Please pull request, if you are in a hurry.

**Comment by enricforn** [comment]
Hi Koji,

Thank you for your response. Some days ago I made a pull request which you
merged to main branch. But you skipped de most important line in parse.js

I did another pull request, in order to show desired information.


Cheers,
Enric

2015-04-07 9:01 GMT+02:00 Koji Ishimoto <notifications@github.com>:
