### ISSUE TITLE
Multicolumn enhancement

### ISSUE THREAD

**Issue by raphaelgoetter** [t32k/stylestats#127]
Hello,

On the result page, and due to CSS3 columns, some `<li>` are broken.

You could use `break-inside` on your `.c-cards` to avoid column breaks : https://css-tricks.com/almanac/properties/b/break-inside/

**Comment by t32k** [comment]
Wow, I wanted to know this prop! Thanks!
I've already update stylestats web.

http://www.stylestats.org/results/VHHYO4QvTH
