### ISSUE TITLE
Plan to drop node 0.10.x

### ISSUE THREAD

**Issue by 1000ch** [t32k/stylestats#129]

**Comment by 1000ch** [comment]
`gzip-size` already drops 0.10.x compatibility.

**Comment by t32k** [comment]
OK, I'll decide the day to drop it.

**Comment by t32k** [comment]
Do I have to update major version to keep Semantic Versioning when we drop node 0.10.x?

**Comment by 1000ch** [comment]
Yes, you should.

**Comment by t32k** [comment]
![JS Girls:confuse](http://tomo-e.github.io/js-girls/images/13.png)

**Comment by 1000ch** [comment]
Node v4.0.0 (Stable)
https://nodejs.org/en/blog/release/v4.0.0

**Comment by t32k** [comment]
I'd like to migrate to v4.0.0 at StyleStats v6.0.0.
