### ISSUE TITLE
Error when parsing an array of URLs

### ISSUE THREAD

**Issue by kaelig** [t32k/stylestats#158]
Steps to reproduce:

### 1. Create a `test.js` file
```js
// test.js
const StyleStats = require('stylestats')
const stats = new StyleStats(['http://cdn.macrumors.com/styles-new/styles.css', 'http://cdn.macrumors.com/styles-new/main.css'])

stats.parse()
  .then(result => console.log(stats.prettify(result)))
  .catch(reason => console.error(reason))
```

### 3. This error is thrown:

```
Error: Error: undefined:3713:24: missing '{'
    at Promise.all.then.then.error (/Users/kdeloumeauprigent/workspace/moniteur/node_modules/stylestats/lib/parser.js:160:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

----

Am I doing something wrong here?

**Comment by kaelig** [comment]
@t32k note that this is something that moniteur has been using and I'd love to see it work in 3.0.0!

**Comment by t32k** [comment]
@kaelig 
`http://cdn.macrumors.com/styles-new/main.css` might be wrong.

Please fix some errors, and retry!
http://www.css-validator.org/validator?uri=http%3A%2F%2Fcdn.macrumors.com%2Fstyles-new%2Fmain.css&profile=css21&usermedium=all&warning=1&lang=en
