### ISSUE TITLE
Font-family + font-size stats

### ISSUE THREAD

**Issue by lafaulx** [t32k/stylestats#68]
Will it be able to gather stats on unique font-family / font-size combinations some day?

**Comment by lafaulx** [comment]
@t32k Is this thing working now or you just closed the issue?

**Comment by t32k** [comment]
StyleStats enables you to know the following metrics:

+ Total Unique Font Families
+ Unique Font Families
+ Total Unique Font Sizes
+ Unique Font Sizes

Is it enough? What metrics do you want? Please let me know more detail. :)

**Comment by lafaulx** [comment]
It's useful to =to know permutations of font families and font sizes – something like:
1. helvetica – 8px, 10px, 12px;
2. arial – 12px, 16px, 18px;
That question was about that kind of data)

**Comment by t32k** [comment]
Hmm, StyleStats can only parse CSS files, it means it cannot analyze cascaded style on the HTML page.
It can `font` metrics as follows.

```
body {
  font: italic small-caps normal 13px/150% Arial, Helvetica, sans-serif;
}
```
