### ISSUE TITLE
LESS/SASS/Stylus etc preprocess support

### ISSUE THREAD

**Issue by paazmaya** [t32k/stylestats#7]
Any change of getting some of those preprocessors supporter, or more specifically, the format they use to be supported?

So that running
```sh
stylestats path/to/stylesheet.less
```
would output similar results with additional mixin usage statistics.

**Comment by woutvdd** [comment]
+1, I used compass stat to generate stats, and send it to a graphite server to visualize it, but since libsass is faster, I've stopped using it.

**Comment by t32k** [comment]
It's related to #140 
As mentioned above, we think that CSS statistics should be collected from CSS.
However, It might be possible to support SCSS files if we move to PostCSS.
