### ISSUE TITLE
@keyframes causes CSS parse error

### ISSUE THREAD

**Issue by MichaelArestad** [t32k/stylestats#75]
Kept getting an error and noted that any `@keyframe` block prevents stylestats from being amazing.

**Comment by t32k** [comment]
@MichaelArestad 
Do you still have the error? Please tell me sample CSS code has the error if you have it.

**Comment by slwfleming** [comment]
I am still seeing this error.

**Comment by t32k** [comment]
@slwfleming What is StyleStats version you use?
I didn't see the error in v5.1.0.

**Comment by slwfleming** [comment]
Version: 5.1.0

This is the exact output from compass of my scss:

@keyframes my-fadein{0%{opacity:0}100%{opacity:1}}

**Comment by t32k** [comment]
What kind of error do you have?
Please paste the error message here.
