### ISSUE TITLE
certain CSS files cause parse error

### ISSUE THREAD

**Issue by jaydestro** [t32k/stylestats#78]
$ stylestats  http://s3-ak.buzzfed.com/static/css/header.css -t json
 [ERROR] CSS parse error.

y$ stylestats  http://s3-ak.buzzfed.com/static/css/header.css -t json
 [ERROR] CSS parse error.

other files seems to work ok. any issue with this particular css?

**Comment by 1000ch** [comment]
I think CSS to send to users (not only to analyze) should be valid.

There is a safe parser that will fix invalid CSS after moving to PostCSS.
(But we are not sure to use it.)
